### ISSUE TITLE
Store user roles when flagging them if they were already in the server

### ISSUE THREAD

**Issue by fredjarjour** [KuriusMTL/KuriusGuard#5]
If a user who is verified is in the server but their account gets hacked and flagged, instead of kicking them it would be useful to remove all roles, store which roles they had, and send them a captcha. When they solve the captcha, the roles would be given back automatically

**Comment by PersoSirEduard** [comment]
Solved #5 in the latest commit 37bb7cf7a95271be6274e4e94976fa0f494cc8fa. When using `!flag`, the user's permissions will be saved and returned after a manual verification.
